[tool.poetry]
name = "scraper-scrapy"
version = "0.1.0"
description = "Scrapy is a scraper tool framework built in python."
authors = ["guimassoqueto <gui.massoqueto@gmail.com>"]
readme = "README.md"
packages = [{include = "scraper_scrapy"}]

[tool.poetry.dependencies]
python = "^3.10"
scrapy = "^2.9.0"
ipython = "^8.14.0"
asyncpg = "^0.27.0"
python-dotenv = "^1.0.0"
fake-useragent = "^1.1.3"
install = "^1.3.5"
scrapy-splash = "^0.9.0"
scrapy-playwright = "^0.0.26"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.2"
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
