CREATE TABLE products (
	"id" VARCHAR(10) PRIMARY KEY NOT NULL,
	"title" VARCHAR(255) NOT NULL,
	"category" VARCHAR(255) NOT NULL,
	"reviews" INTEGER NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
);